version: 0.2

phases:
  pre_build:
    commands:
      - echo dependencies
      - mvn clean install
      - echo Logging in to Amazon ECR....
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/t8g7f8a1
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t onbaordingimage .
      - docker tag onbaordingimage:latest public.ecr.aws/t8g7f8a1/onbaordingimage:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image......
      - docker push public.ecr.aws/t8g7f8a1/onbaordingimage:latest
artifacts:
  files:
    - target/lk-backend-0.0.1-SNAPSHOT.jar lk-backend-0.0.1-SNAPSHOT.jar
    - imagedefinitions.json