spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://lendingking-database.cfe6um8osgik.ap-south-1.rds.amazonaws.com:3306/lendingking?createDatabaseIfNotExist=true
    username: admin
    password: ${SPRING_PROD_DATASOURCE_PASSWORD:}
  flyway:
    locations: classpath:db/migration
