spring:
  security:
    user:
      name: user
      password: user

  datasource:
    url: jdbc:mysql://database-onboarding.cbgii4kmmlyn.eu-north-1.rds.amazonaws.com:3346/database-onboarding?createDatabaseIfNotExist=true
    username: admin
    password: ${SPRING_DATASOURCE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# AWS S3 Configuration
aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID:}
  secretKey: ${AWS_SECRET_ACCESS_KEY:}
  region: eu-north-1
  s3:
    bucketName: application-details

msg91:
  authkey: ${MSG91_AUTH_KEY:}
  verify-otp-url: "https://control.msg91.com/api/v5/otp/verify"
  send-otp-url: "https://control.msg91.com/api/v5/otp"
  send-email-url: "https://control.msg91.com/api/v5/email/send"
