spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://lendingking-test.cfe6um8osgik.ap-south-1.rds.amazonaws.com:3306/lendingking-test?createDatabaseIfNotExist=true
    username: admin
    password: ${SPRING_TEST_DATASOURCE_PASSWORD:}
  flyway:
    locations: classpath:db/migration,classpath:db/test-migration
