name: Build and Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - PlayStore
      - Test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Make Maven Wrapper Executable
      run: chmod +x mvnw

    - name: Update application.yml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'src/main/resources/application.yml'
        changes: |
          {
            "spring.profiles.active": "${{ secrets.SPRING_PROD_DATASOURCE_PASSWORD }}"
          }
        commitChange: false

        
    - name: Print modified YAML
      run: cat src/main/resources/application.yml

    - name: Build Spring Boot Application
      run: |
        if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/PlayStore" ]; then
          ./mvnw clean package -Dmaven.test.skip=true -Dspring.profiles.active=prod
        elif [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/Test" ]; then
          ./mvnw clean package -Dmaven.test.skip=true -Dspring.profiles.active=test
        else
          echo "Skipping build for event: ${{ github.event_name }} and ref: ${{ github.ref }}"
        fi

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event_name == 'push' && github.ref == 'refs/heads/Test' && 'eu-central-1' || 'eu-north-1' }}

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ github.event_name == 'push' && github.ref == 'refs/heads/PlayStore' && 'LendingKing' || 'lendingking-test' }}
        environment_name: ${{ github.event_name == 'push' && github.ref == 'refs/heads/PlayStore' && 'my-spring-boot-app-test-env' || 'Lendingking-test-env' }}
        version_label: ${{ github.run_id }}
        region:  ${{ github.event_name == 'push' && github.ref == 'refs/heads/Test' && 'eu-central-1' || 'eu-north-1' }}
        deployment_package: target/lk-backend-0.0.1-SNAPSHOT.jar
